name: gallery
description: "A new Flutter project."
publish_to: 'none'
version: 0.4.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  file_picker: ^8.0.3
  shared_preferences: ^2.2.3
  watcher: ^1.1.0
  path: ^1.9.0
  path_provider: ^2.1.3
  flutter_typeahead: ^5.2.0
  image: ^4.1.0
  launch_at_startup: ^0.3.1
  package_info_plus: ^8.0.0
  
  # NUEVO: Para gestionar el icono y menú de la bandeja del sistema.
  tray_manager: ^0.2.1
  # NUEVO: Para controlar la ventana de la aplicación (ocultar, mostrar, cerrar).
  window_manager: ^0.3.8

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # NUEVO: Asegúrate de tener una carpeta 'assets' con un icono para la app.
  assets:
    - assets/

